"""add_autopilot_and_source_fields

Revision ID: 92be7b789d56
Revises: 37ba5d7d7d45
Create Date: 2026-03-03 00:35:04.758139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92be7b789d56'
down_revision: Union[str, None] = '37ba5d7d7d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('is_autopilot', sa.Boolean(), nullable=True))
    op.add_column('businesses', sa.Column('website_url', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('specific_page_url', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('category', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('content_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_campaigns_content_hash'), 'campaigns', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaigns_content_hash'), table_name='campaigns')
    op.drop_column('campaigns', 'content_hash')
    op.drop_column('businesses', 'category')
    op.drop_column('businesses', 'specific_page_url')
    op.drop_column('businesses', 'website_url')
    op.drop_column('businesses', 'is_autopilot')
    # ### end Alembic commands ###
