"""add logo_url to business

Revision ID: 95743f5fce48
Revises: a9bf24d5d401
Create Date: 2026-03-03 17:56:57.282537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95743f5fce48'
down_revision: Union[str, None] = 'a9bf24d5d401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('logo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'logo_url')
    # ### end Alembic commands ###
