"""add_posting_frequency

Revision ID: a9bf24d5d401
Revises: 92be7b789d56
Create Date: 2026-03-03 01:02:12.844535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9bf24d5d401'
down_revision: Union[str, None] = '92be7b789d56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('posting_frequency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'posting_frequency')
    # ### end Alembic commands ###
